# UI defaults configuration file. It is automatically loaded if located at configs/webui/webui_streamlit.yaml.
# Any changes made here will be available automatically on the web app without having to stop it.
# You may add overrides in a file named "userconfig_streamlit.yaml" in this folder, which can contain any subset
# of the properties below.
general:
    gpu: 0
    outdir: outputs
    default_model: "Stable Diffusion v1.4" 
    default_model_config: "configs/stable-diffusion/v1-inference.yaml"
    default_model_path: "models/ldm/stable-diffusion-v1/model.ckpt"
    use_sd_concepts_library: True
    sd_concepts_library_folder: "models/custom/sd-concepts-library"
    GFPGAN_dir: "./src/gfpgan"
    RealESRGAN_dir: "./src/realesrgan"
    RealESRGAN_model: "RealESRGAN_x4plus"
    LDSR_dir: "./src/latent-diffusion"
    outdir_txt2img: outputs/txt2img-samples
    outdir_img2img: outputs/img2img-samples
    gfpgan_cpu: False
    esrgan_cpu: False
    extra_models_cpu: False
    extra_models_gpu: False
    save_metadata: True
    save_format: "png"
    skip_grid: False
    skip_save: False
    grid_format: "jpg:95"
    n_rows: -1
    no_verify_input: False
    no_half: False
    use_float16: False
    precision: "autocast"
    optimized: False
    optimized_turbo: False
    optimized_config: "optimizedSD/v1-inference.yaml"
    enable_attention_slicing: False
    enable_minimal_memory_usage : False
    update_preview: True
    update_preview_frequency: 10

txt2img:
    prompt:
    width:
        value:      512
        min_value:  64
        max_value:  2048
        step:       64
        
    height:
        value:      512
        min_value:  64
        max_value:  2048
        step:       64
        
    cfg_scale:
        value:      7.5
        min_value:  1.0
        max_value:  30.0
        step:       0.5

    seed: ""
    batch_count:
        value:      1
        min_value:  1
        max_value:  100
        step:       1
        
    batch_size:
        value:      1
        min_value:  1 
        max_value:  5
        step:       1
        
    sampling_steps:
        value:      30
        min_value:  10
        max_value:  250
        step:       10

    default_sampler: "k_euler"
    separate_prompts: False
    update_preview: True
    update_preview_frequency: 10
    normalize_prompt_weights: True
    save_individual_images: True
    save_grid: True
    group_by_prompt: False
    save_as_jpg: False
    use_GFPGAN: False
    use_RealESRGAN: False
    RealESRGAN_model: "RealESRGAN_x4plus"
    
    variant_amount:
        value:      0.0
        min_value:  0.0
        max_value:  1.0
        step:       0.01
        
    variant_seed: ""
    write_info_files: True
    
txt2vid:
    default_model: "CompVis/stable-diffusion-v1-4"
    custom_models_list: ["CompVis/stable-diffusion-v1-4", "naclbit/trinart_stable_diffusion_v2", "hakurei/waifu-diffusion", "osanseviero/BigGAN-deep-128"]
    prompt:
    width:
        value:      512
        min_value:  64
        max_value:  2048
        step:       64
        
    height:
        value:      512
        min_value:  64
        max_value:  2048
        step:       64
        
    cfg_scale:
        value:      7.5
        min_value:  1.0
        max_value:  30.0
        step:       0.5
        
    batch_count:
        value:      1
        min_value:  1
        max_value:  100
        step:       1
        
    batch_size:
        value:      1
        min_value:  1 
        max_value:  5
        step:       1
        
    sampling_steps:
        value:      30
        min_value:  10
        max_value:  250
        step:       10
        
    num_inference_steps:
        value:      200
        min_value:  10
        max_value:  500
        step:       10
        
    seed: ""
    default_sampler: "k_euler"
    scheduler_name: "klms"
    separate_prompts: False
    update_preview: True
    update_preview_frequency: 10
    dynamic_preview_frequency: True
    normalize_prompt_weights: True
    save_individual_images: True
    save_video: True
    group_by_prompt: True
    write_info_files: True
    do_loop: False
    save_as_jpg: False
    use_GFPGAN: False
    use_RealESRGAN: False
    RealESRGAN_model: "RealESRGAN_x4plus"
    variant_amount:
        value:      0.0
        min_value:  0.0
        max_value:  1.0
        step:       0.01
        
    variant_seed: ""
    
    beta_start:
        value:      0.00085
        min_value:  0.0001
        max_value:  0.0300
        step:       0.0001
        format:     "%.5f"
        
    beta_end:
        value:      0.012
        min_value:  0.0001
        max_value:  0.0300
        step:       0.0001
        format:     "%.5f"
        
    beta_scheduler_type: "linear"
    max_frames: 100
    
img2img:
    prompt: 
    sampler_name: "k_euler"
    denoising_strength: 
        value:      0.75
        min_value:  0
        max_value:  1
        step:       0.1
    # 0: Keep masked area
    # 1: Regenerate only masked area
    mask_mode: 0
    mask_restore: False
    # 0: Just resize
    # 1: Crop and resize
    # 2: Resize and fill
    resize_mode: 0
    # Leave blank for random seed:
    seed: ""
    ddim_eta: 0.0
    width:
        value:      512
        min_value:  64
        max_value:  2048
        step:       64
        
    height:
        value:      512
        min_value:  64
        max_value:  2048
        step:       64
        
    cfg_scale:
        value:      7.5
        min_value:  1.0
        max_value:  30.0
        step:       0.5
        
    batch_count:
        value:      1
        min_value:  1
        max_value:  100
        step:       1
        
    batch_size:
        value:      1
        min_value:  1 
        max_value:  5
        step:       1
        
    sampling_steps:
        value:      30
        min_value:  10
        max_value:  250
        step:       10
        
    num_inference_steps:
        value:      200
        min_value:  10
        max_value:  500
        step:       10
        
    find_noise_steps:
        value:      100
        min_value:  0
        max_value:  500
        step:       10
        
    loopback: True
    random_seed_loopback: True
    separate_prompts: False
    update_preview: True
    update_preview_frequency: 10
    normalize_prompt_weights: True
    save_individual_images: True
    save_grid: True
    group_by_prompt: False
    save_as_jpg: False
    use_GFPGAN: False
    use_RealESRGAN: False
    RealESRGAN_model: "RealESRGAN_x4plus"
    variant_amount: 0.0
    variant_seed: ""
    write_info_files: True
    
gfpgan:
  strength: 100
