plugins:
  - jekyll-relative-links
  - jekyll-readme-index
  - jemoji
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
source: docs
remote_theme: pages-themes/midnight@v0.2.0
