plugins:
  - jekyll-relative-links
  - jekyll-readme-index
  - jemoji
relative_links:
  enabled: true
  collections: true
source: docs
theme: minima
include:
  - CONTRIBUTING.md
#  - README.md
  - LICENSE.md
