version: '3.3'

services:
  stable-diffusion:
    container_name: sd-webui
    image:  stable-diffusion-webui:dev

    env_file: .env_docker

    volumes:
      - .:/sd
      - ./outputs:/sd/outputs
      - ./model_cache:/sd/model_cache
      - root_profile:/root
    ports:
      - '7860:7860'
      - '8501:8501'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

volumes:
  root_profile:
