version: '3.3'

services:
  stable-diffusion:
    container_name: sd-webui
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env_docker
    volumes:
      - .:/sd
      - ./outputs:/sd/outputs
      - ./model_cache:/sd/model_cache
      - conda_env:/opt/conda
      - root_profile:/root
    ports:
      - '7860:7860'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

volumes:
  conda_env:
  root_profile:
